app/views/auth.py
from flask import Blueprint , render_template , request , session
from flask_wtf.csrf import CSRFProtect
import re
from werkzeug.utils import secure_filename
import os
from ..models.myusers import myusers , CamLink ,CamLink2
from ..models.myusers import db
from ..models.image import image
from flask_session import Session

from .. import app

auth = Blueprint('auth',__name__)
UPLOAD_FOLDER = 'static/uploads'
app.config['UPLOAD_FOLDER'] = "D:/programming/ITI/Flask/alproject/app/static/uploads"
app.config["SESSION_PERMANENT"] = False
app.config["SESSION_TYPE"] = "filesystem"
Session(app)
@auth.route('/login', methods=['GET','POST'])
def login():
    title='Login'
    if request.method == 'GET':
        return render_template('auth/login2.html',title=title)
    else:
        email = request.form['email']
        password = request.form['password']
        myresult1 = myusers.query.filter_by(email=email , password= password).first()
        # print("my result is here pls",myresult1.firstname)
        if(myresult1 != None):
            firstname = myresult1.firstname
            email = myresult1.email
            username = myresult1.username
            lastname = myresult1.lastname
            fullname = firstname + ' ' + lastname
            session['username'] = fullname
            session['email'] = email
            # session['user'] = user
            session['firstname'] = firstname
            return render_template('home/home.html',fullname = fullname)           
        else:
            emailpass = 'email and/or password are not correct'
            return render_template('auth/login2.html',emailpass=emailpass)


        


@auth.route('/register', methods=['GET','POST'])
def register():
    # app_root = os.path.dirname(os.path.abspath(__file__))
    # target = os.path.join(app_root, 'static/uploads/')
    # target = os.path.join('D:/programming/ITI/Flask/alproject/app/static/uploads')
    # if not os.path.isdir(target):
    #     os.makedirs(target)

    title='Register'
    if request.method == 'GET':
        return render_template('auth/register.html',title=title)

    else:
        # image = request.files['image']
        # filename = secure_filename(image.filename)
        # destination = '/'.join([target, filename])
        # image.save(destination)
        # image.save(os.path.join(app.config['UPLOAD_FOLDER'] , filename))

        username=request.form['username']
        firstname=request.form['firstname']
        lastname=request.form['lastname']
        email=request.form['email']
        password1=request.form['password']
        address=request.form['address']
        country=request.form['country']
        bdate=request.form['bdate']
        print(username,firstname,lastname,password1,email,bdate,address,country)
        name_regex = r"^[a-zA-Z ,.'-]+$"
        email_regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b'

        myresult1 = myusers.query.filter_by(email=email).first()
        
        myresult2 = myusers.query.filter_by(username=username).first()
        if(myresult2):
            print(myresult1,"my result 1 ")
            userxists = 'this username  already exists'
            print("username already exists")
            return render_template('auth/register.html', userxists=userxists)

        elif(myresult1 != None):

            emailexists = 'this email  already exists'
            print("username already exists")

            return render_template('auth/register.html', emailexists=emailexists)


        if (re.search(name_regex, request.form['firstname']) == None):
            
            errorfname = 'This First Name Is Not Valid Enter Valid Name'
            return render_template('auth/register.html', errorfname=errorfname)
        else:
            print("firstname is valid")
        if (re.search(name_regex, request.form['username']) == None):
          
            errorusername = 'This userName Is Not Valid Enter Valid userName'
            return render_template('auth/register.html', errorusername=errorusername)
        else:
            print("username is valid")
        if (re.search(name_regex, request.form['lastname']) == None):
          
            errorlastname = 'This lastname Is Not Valid Enter Valid lastname'
            return render_template('auth/register.html', errorlastname=errorlastname)
        else:
            print("lastname is valid")
        if (re.search(email_regex, request.form['email']) == None):
          
            erroremail = 'This email Is Not Valid Enter Valid email'
            return render_template('auth/register.html', erroremail=erroremail)
        else:
            print("email is valid")
        if (request.form['password'] == request.form['confirm']):
            # if image:
            #     filename = secure_filename(image.filename)
            #     image.save(os.path.join(app.config['UPLOAD_FOLDER'] , filename))

            newuser = myusers(username = username , firstname = firstname , lastname = lastname , password = password1
            , email = email , country = country , Address = address , bdate = bdate )
            db.session.add(newuser)
            db.session.commit()
            fullname = firstname + ' ' + lastname
            return render_template('auth/login2.html',fullname = fullname)
        else:
            
            notequal = "password must be identical"
            return render_template('auth/register.html', notequal=notequal)



@auth.route('/logout')
def logout():
    myemail= session['email']
    CamLink.query.filter_by(email=myemail).delete()
    CamLink2.query.filter_by(email=myemail).delete()
    db.session.commit()
    session.clear()
    return render_template('home/welcome.html')

app/views/home.py
from asyncio.windows_events import NULL
from email import message
from flask import Blueprint , render_template , request , send_from_directory , session , jsonify , json
from werkzeug.utils import secure_filename
from ..models.image import image
from ..models.myusers import Myvideo , Myvideo2 , image2 , CamLink , CamLink2 , LiveCam , EventVO , EventVE , EventCO ,EventCE
from ..models import db
home = Blueprint('home', __name__)
from .. import app
import os
from os.path import join, dirname, realpath
from flask_session import Session
import validators



UPLOADS_PATH = join(dirname(realpath(__file__)), 'static/uploads/..')

# app.config['UPLOAD_FOLDER'] = "/D:/programming/ITI/Flask/alproject/app/static/uploads"
app.config['UPLOAD_FOLDER'] = UPLOADS_PATH
app_root = os.path.dirname(os.path.abspath(__file__))
target = os.path.join(app_root, 'static/uploads/')
target2 = os.path.join(app_root, 'static2/uploads2/')
# target = os.path.join('D:/programming/ITI/Flask/alproject/app/static/uploads')
if not os.path.isdir(target):
    os.makedirs(target)

if not os.path.isdir(target2):
    os.makedirs(target2)

@home.route('/home')
def home_page():
    
    if session.get('email') == None:
        return render_template('error/notfound.html')
    else:

        myemail = session['email']
        fullname = session['username']
        firstname = session['firstname']
        return render_template('home/home.html',myemail = myemail , firstname = firstname,fullname = fullname)


@home.route('/')
def welcome_page():
    return render_template('home/welcome.html')

@home.route('/analytics')
def analytic_page():

    if session.get('email') == None:
        return render_template('error/notfound.html')
    else:
        myname= session['username']
        myemail= session['email']
        firstname= session['firstname']
        return render_template('home/Analytics.html',myname = myname,myemail = myemail , firstname = firstname)


@home.route('/object_det')
def object_page():
    
    if session.get('email') == None:
        return render_template('error/notfound.html')
    else:
        myname= session['username']
        myemail= session['email']
        firstname= session['firstname']

        return render_template('home/objectDet.html',myname = myname ,myemail = myemail ,firstname = firstname)


@home.route('/emotion_det')
def emotion_page():
    
    if session.get('email') == None:
        return render_template('error/notfound.html')
    else:
        myname= session['username']
        myemail= session['email']
        firstname= session['firstname']

        return render_template('home/emotionalDet.html',myname = myname,myemail = myemail ,firstname = firstname)

@app.route('/file/<filename>')
def get_image(filename):
    return send_from_directory(target, filename)

@app.route('/file2/<filename>')
def get_image2(filename):
    return send_from_directory(target2, filename)

# for object detection
@home.route('/upload_image' , methods = ['GET','POST'])
def upload_image():
    
    if session.get('email') == None:
        return render_template('error/notfound.html')
    else:

        myname= session['username']
        myemail= session['email']
        firstname= session['firstname']

        if request.method == 'GET':
            myid = 0 
            return render_template('home/uploadImage.html', myid = myid ,myname = myname,myemail = myemail ,firstname = firstname)
        else:
            
            myimage = request.files['image']
            processor = request.form['radio']

            # myimage.save(os.path.join(app.config['UPLOAD_FOLDER'], myimage.filename))


            filename = secure_filename(myimage.filename)
            destination = '/'.join([target, filename])
            print(destination, "destination ...............................")
            myimage.save(destination)
            # myimage.save(os.path.join(app.config['UPLOAD_FOLDER'] , filename))
            print("image saved")
            print("image id is :",myimage)
            print("image processor is :",processor)
            print("image file name :",myimage.filename)
            print("image mimetype :",myimage.mimetype)
            if not myimage:
                uploadimg = 'please upload an image'
                return render_template('home/uploadImage.html',uploadimg = uploadimg ,myname =myname,myemail = myemail ,firstname = firstname)
            else:
                filename = secure_filename(myimage.filename)
                mimetype = myimage.mimetype
                newimage = image(mimetype= mimetype , name=filename , processor = processor , img =myimage.read())
                db.session.add(newimage)
                db.session.commit()
                idd = newimage.id
                print("newwwwwwwwwwwww id dis :  " ,idd)
                # myid = myimage.id
                uploaded = 'your image uploaded successfully'
                return render_template('home/uploadImage.html', uploaded = uploaded , myid = idd ,myname = myname,myemail = myemail ,firstname = firstname)







@home.route('/predict_image/<int:id>')
def predict_image(id):
    
    if session.get('email') == None:
        return render_template('error/notfound.html')
    else:

        myname= session['username']
        myemail= session['email']
        firstname= session['firstname']
        myimage = image.query.filter_by(id=id).first()
        print(myimage.name , "here is your image 2022")
        print(myimage.mimetype , "here is your mimetype 2022")
        filename = myimage.name

        return render_template('home/imagePrediction.html', filename = filename,myname = myname,myemail = myemail ,firstname = firstname)


@home.route('/upload_vedio' , methods=['GET','POST'])
def upload_vedio():
    
    if session.get('email') == None:
        return render_template('error/notfound.html')
    else:
            
        myname= session['username']
        myemail= session['email']
        firstname= session['firstname']
        if request.method == 'GET':
            myid = 0
            return render_template('home/uploadvedio.html', myid = myid ,myname = myname,myemail = myemail ,firstname = firstname)
        else:
            processor = request.form['radio']

            myved = request.files['video']
            filename = secure_filename(myved.filename)
            destination = '../'.join([target, filename])
            print(destination, "destination ...............................")
            myved.save(destination)
            if not myved:
                uploadvedio = 'please upload a video'
                return render_template('home/uploadvedio.html',uploadvedio = uploadvedio ,myname=myname,myemail = myemail ,firstname = firstname)
            else:
                filename = secure_filename(myved.filename)
                # name = myved.name
                newved = Myvideo( name=filename , processor=processor)
                db.session.add(newved)
                db.session.commit()
                idd = newved.id
                print("newwwwwwwwwwwww id dis :  " ,idd)
                # myid = myimage.id
                uploaded = 'your video uploaded successfully'
                return render_template('home/uploadvedio.html', uploaded = uploaded , myid = idd ,myname = myname,myemail = myemail ,firstname = firstname)


@home.route('/predict_vedio/<int:id>')
def predict_vedio(id):
    
    if session.get('email') == None:
        return render_template('error/notfound.html')

    else:
            
        myname= session['username']
        myemail= session['email']
        firstname= session['firstname']

        myved = Myvideo.query.filter_by(id=id).first()
        filename = myved.name
        myid = id
        return render_template('home/vedioPrediction.html' ,myid=myid,filename = filename, myname =myname,myemail = myemail ,firstname = firstname)



# for emotional  detection =====================================================================

# =============================================================================================
# =============================================================================================
# =============================================================================================
# =============================================================================================


@home.route('/upload_image_emo' , methods = ['GET','POST'])
def upload_image_emo():
    
    if session.get('email') == None:
        return render_template('error/notfound.html')
    else:

        myname= session['username']
        myemail= session['email']
        firstname= session['firstname']
        if request.method == 'GET':
            myid = 0
            return render_template('home/uploadImageEmo.html', myid = myid ,myname = myname,myemail = myemail ,firstname = firstname)
        else:
            processor = request.form['radio']

            
            myimage = request.files['image']
            # myimage.save(os.path.join(app.config['UPLOAD_FOLDER'], myimage.filename))


            filename = secure_filename(myimage.filename)
            destination = '/'.join([target2, filename])
            print(destination, "destination ...............................")
            myimage.save(destination)
            # myimage.save(os.path.join(app.config['UPLOAD_FOLDER'] , filename))
            print("image saved")
            print("image id is :",myimage)
            print("image file name :",myimage.filename)
            print("image mimetype :",myimage.mimetype)
            if not myimage:
                uploadimg = 'please upload an image'
                return render_template('home/uploadImageEmo.html',uploadimg = uploadimg ,myname =myname,myemail = myemail ,firstname = firstname)
            else:
                filename = secure_filename(myimage.filename)
                mimetype = myimage.mimetype

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- required meta tags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}
        {%endblock%}</title>
    <!-- bootstrap , fontawsome , custom css -->
  
    {%block style%}
    {%endblock%}
    <link rel="stylesheet" href="{{url_for('static' , filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static' , filename='css/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static' , filename='css/home.css')}}">
    <script src="https://kit.fontawesome.com/a1aef19155.js" crossorigin="anonymous"></script>
 


</head>
<body>  
    <!-- start of navbar -->
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <img src="{{url_for('static' , filename='images/logo.jpeg')}}" alt="Navbar Logo" class="logo border rounded " />

        <a class="navbar-brand" href="#">AI Predict</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="">Home <span class="sr-only"></span></a>
            </li>

          </ul> -->
          <!-- Navbar Right Side -->
          <ul class="navbar-nav">
                <li class="nav-item element">
                    <a class="nav-link" href="{{ url_for('home.home_page') }}">Home</a>
                    <!-- " -->
                </li>
   
              <li class="nav-item element">
                <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                <!-- {{ url_for('auth.login') }}" -->
              </li>
              <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                <!-- {{ url_for('home.home_page') }} -->
              </li>
      
              <li class="nav-item ">
                <a class="nav-link" href="#">Profile</a>
              </li>
              <li class="nav-item element1">
                <a class="nav-link" href="">logout</a>
                <!-- {{ url_for('home.home_page') }} -->
              </li>
           
          </ul>
        </div>
      </nav>

      <!-- end of navbar -->
    {% block content %}
    {% endblock %}


        <!-- end of body -->




    <!-- footer -->
    <div class="footer" >
        <div class="container">
            <div class="box me-5 " >
                <h3>AI Prediction</h3>
                <ul class="social">
                    <li>
                        <a href="#" class="facebook">
                            <!-- <i class="fab fa-facebook-f"></i> -->
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="twitter">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="youtube">
                            <i class="fab fa-youtube"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="instagram">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                    </li>
                </ul>
                <p class="text">
                    Your local AI Services in Saudi Arabia.
                    We Are Pleased href Provide A Nation-Wide Variety Of AI Services.
                </p>
            </div>

            <div class="box ms-5">
                <div class="line">
                    <i class="fas fa-map-marker-alt fa-fw"></i>
                    <div class="info">SA, Gadda, Inside The Sphinx, Room Number 220</div>
                </div>
                <div class="line">
                    <i class="fa-solid fa-clock"></i>
                    <div class="info">Business Hours: From 10:00 To 18:00</div>
                </div>
                <div class="line">
                    <i class="fas fa-phone-volume fa-fw"></i>
                    <div class="info">
                        <span>+20123456789</span>
                        <span>+20198765432</span>
                    </div>
                </div>
            </div>
            <div class="box p-5 ">
                <img src="{{url_for('static' , filename='images/logo.jpeg')}}" alt="Navbar Logo" class="mylogo border rounded " />
             


            </div>
        </div>
        <p class="copyright">Made With &lt;3 By AI Team</p>
    </div>



    <!-- jquery and custom js -->
    <script src="{{url_for('static', filename='js/jquery.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
</body>
</html>